### ISSUE TITLE
안녕하세요 에브리타임 보고 이슈 남겨드려요

### ISSUE THREAD

**Issue by Neulhan** [POMMI3R/kimde#1]
혹시 해당 기능 같이 협업해서 웹 어플리케이션으로 만들어보실 생각은 없으신가요?
비 개발자 사용자들이 좀 더 쉽게 접근하게 만들어 볼 수 있을 것 같아요!

**Comment by kimhappy** [comment]
이미 꽤 많은 분들이 쓰고 계신데, 크롬드라이버를 그렇게 자주 돌리는 서버를 빌리는건 비용이 좀 발생할것 같네요...

사비를 들이거나 공식 후원을 열 생각은 없습니다.

**Comment by kimhappy** [comment]
GPLv3로 배포하고 있으니 라이선스 맞춰서 소스 가져다 쓰시는건 괜찮습니다.

웹 어플리케이션 경험은 없지만, Rust 프로그래밍이나 kimde 소스 해석은 도와드릴 수 있습니다.

**Comment by Neulhan** [comment]
redis 로 웹드라이버 사용빈도를 최소한으로 줄이면서 한 번 테스트 버전을 만들어보고 싶긴 하네요.
라이센스 맞춰가며 개발해볼테니 잘 모르겠는 부분있으면 여쭤보겠습니다!

**Comment by Neulhan** [comment]
이슈는 일단 닫아둘게요
